# Configurazione Marp per export CLI
# inputDir: .  # Commentato per permettere export di file singoli
themeSet:
  - ./template/themes/master.scss
  - ./template/themes/alma.scss
html: true
allowLocalFiles: true
